
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"

	#config.vm.provision :docker
  #config.vm.provision :docker_compose
  
	config.vm.network :forwarded_port,
	  guest: 22,
	  host: 2201,
	  id: "ssh",
	  auto_correct: true
	
	config.vm.network :forwarded_port,
	  guest: 943,
	  host: 943,
	  id: "openvpn_webui",
	  auto_correct: true
	
	config.vm.network :forwarded_port,
	  guest: 443,
	  host: 443,
	  id: "openvpn_vpn_tcp",
	  auto_correct: true
	  
	config.vm.network :forwarded_port,
	  guest: 1194,
	  host: 1194,
	  protocol: "udp",
	  id: "openvpn_vpn_udp",
	  auto_correct: true

  config.vm.hostname = "ubuntu.local"

  config.vm.provision "shell", path: "./openvpn.sh"

  config.vbguest.auto_update = false


	config.vm.provider "virtualbox" do |vb|
		vb.customize ["modifyvm", :id, "--ioapic", "on"]
		vb.memory = "2048"
		vb.cpus = 2
		vb.name = "ubuntu.local"
    end

end
 